### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by luke187** [Rinnegatamante/ZeldaOLB#2]
After you beat the boss and gab the 5th cup in the level 8 and the guy that splits from you finishes talking the game freezes and the vita is forced to restart. This happens every time I grab the cup. I have tried it about 5 times and the same thing happens each time.

**Comment by Rinnegatamante** [comment]
Can you upload a save near the boss? Need to debug it in order to fix it.

**Comment by luke187** [comment]
Sure where would I find the safe file to upload it?

**Comment by Rinnegatamante** [comment]
ux0:/data/ZeldaOLB

**Comment by luke187** [comment]
I think this is the save file. I placed it in a folder and zipped it because the sight would not accept it how it was.
[untitled folder 2.zip](https://github.com/Rinnegatamante/ZeldaOLB/files/1052686/untitled.folder.2.zip)

**Comment by Rinnegatamante** [comment]
Seems like a GPU crash, that would be quite difficult to debug cause no useful crashdump is properly produced with these kind of crashes.

**Comment by luke187** [comment]
I tried using my save data with the psp port and it freezes at the same spot.

**Comment by Rinnegatamante** [comment]
That's an interesting find. Would be interesting to know if the same issue appears on the 3DS port (PSVITA version is based off of it).

**Comment by luke187** [comment]
It sounds like its a problem with the original game or port. I don't have a 3DS to try that port.

**Comment by Rinnegatamante** [comment]
Well, i really doubt it's an issue with the original game, if you want to try it however, you can grab it here: http://www.zeldaroth.fr/us/zolb.php

**Comment by luke187** [comment]
well in the original game i can get past that point and save but when I move the save file back to the vita and try to play from that point on it loads up and i have to fight the boss again to get the cup again and the game still crashes. on the vita there are 2 files in the save folder but on the pc there is only one file in the fave folder could that have anything to do with it?

**Comment by luke187** [comment]
I got the save data to work on the psp version of the game but when i move it to the vita version of the game my save data does not show up
