### ISSUE TITLE
GPU crash when entering a secret entrance under a bush near where pit and zelda are in the house.

### ISSUE THREAD

**Issue by nightwishfan1** [Rinnegatamante/ZeldaOLB#3]
I have a core dump for the above occurrence that reads out as such:

Exception  Unknown cause
Thread ID  0xFFFFFFFF
Thread name
EPC   0xFFFFFFFF
Cause   0xFFFFFFFF
BadVAddr   0xFFFFFFFF

a1:  0x81A9AD70   a2:  0x00000000   a3:  0x00055D70  a4:  0x8300ABB0
v1:  0x00A3B450  v2:  0x005C4BB0  v3:  0x00000000  v4:  0x00000000 
v5:  0x810E1CBD  v6:  0x810E1CC5  v7:  0x00000000  v8:  0x00000040
ip:  0x376E4F98  sp:   0x00000000   ir:  0x7FF8DEAD  pc:  0x7F80DEAD

**Comment by Rinnegatamante** [comment]
Coredumps read with VitaShell are useless (especially a gpu one <.<). Ideally i would need a savedata if the crash is easily reproduceable.

**Comment by nightwishfan1** [comment]
I'd provide one but did not save prior to this crash.  I'll have to play back to that point and get to where it did crash.

Edit:  Seems the crashes are getting worse.  Game crashed out to live area playing the haunted mansion.  However this wasn't a gpu type, which doesn't seem to be easy to reproduce.

**Comment by nightwishfan1** [comment]
Well now I can't get back to where the gpu crash occurred, cause of a crash when learning the first ocarina song after the haunted mansion.  It's easy to get to from my save point at the haunted mansion dungeon as you only need to move a few blocks down into town.  I was able to progress past that earlier, but now the game crashes out to the live area just after learning it, and I now can't progress beyond it to where the gpu crash occurred.  I believe the olb1.dat file is the one you need as the save file right?  Also to note the sound when learning the song is garbled sounding.  Some sounds in the game sound this way after a while as well.  Like vanquishing enemies and such.
[olb1.zip](https://github.com/Rinnegatamante/ZeldaOLB/files/1958346/olb1.zip)

**Comment by Rinnegatamante** [comment]
You shouldn't encounter anymore crashes with this, can you run a test trying to reach that secret entrance again?
[ZeldaOLB.zip](https://github.com/Rinnegatamante/ZeldaOLB/files/1960876/ZeldaOLB.zip)

**Comment by ChrisHighwind** [comment]
I just tried it out myself, and I was able to get the elegy of emptiness song and enter the bush secret in the woods with no crashes.

**Comment by nightwishfan1** [comment]
Ok that fixed it.  Though I'm noticing some slowdowns in the mountain area where the titan gloves are obtained.  Low FPS ranging from roughly 20-22FPS at that particular point since you got a counter at the top.  Going through the secret entrance under the bush was fine, however the game didn't immediately register that I was standing over the hole for it to let Link fall into it.  It did happen however after a few seconds.
